# Generated by Django 5.0b1 on 2023-12-17 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Number', models.CharField(max_length=15)),
                ('NatCode', models.CharField(max_length=10)),
                ('BirthDate', models.DateField()),
                ('Telephon', models.CharField(max_length=11)),
                ('Mobile', models.CharField(max_length=11)),
                ('Address', models.CharField(max_length=50)),
                ('DateOfEntering', models.DateField()),
                ('Educationalstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.status')),
                ('Majors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.major')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.gender')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
