# Generated by Django 5.0b1 on 2023-12-17 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='field_of_study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Educationalstatus',
            new_name='Status',
        ),
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instructors_Number', models.CharField(max_length=15)),
                ('NatCode', models.CharField(max_length=10)),
                ('BirthDate', models.DateField()),
                ('Telephon', models.CharField(max_length=11)),
                ('Mobile', models.CharField(max_length=11)),
                ('Address', models.CharField(max_length=50)),
                ('DateOfemployeement', models.DateField()),
                ('Majors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.field_of_study')),
                ('Status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.status')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.gender')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
