# Generated by Django 5.0b1 on 2023-12-17 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_field_of_study_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructors',
            name='Majors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.major'),
        ),
        migrations.DeleteModel(
            name='field_of_study',
        ),
    ]
