# Generated by Django 5.0b1 on 2023-12-17 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='description',
        ),
        migrations.RemoveField(
            model_name='major',
            name='description',
        ),
    ]
