# Generated by Django 5.0b1 on 2023-12-17 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_courses_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semesters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Course_Offerings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_Entity', models.IntegerField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.courses')),
                ('instructors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.instructors')),
                ('semester', models.ManyToManyField(to='students.semesters')),
            ],
        ),
    ]
