# Generated by Django 4.2.7 on 2023-12-17 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.courses'),
        ),
        migrations.RemoveField(
            model_name='grades',
            name='student',
        ),
        migrations.AddField(
            model_name='grades',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
