# Generated by Django 4.2.7 on 2023-12-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_grades_course_remove_grades_student_grades_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='grade',
            field=models.IntegerField(max_length=20),
        ),
    ]
