# Generated by Django 4.2.7 on 2023-12-22 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='Instructors',
        ),
        migrations.AddField(
            model_name='courses',
            name='Instructors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.instructors'),
        ),
    ]
