# Generated by Django 4.2.7 on 2023-12-22 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_remove_courses_instructors_courses_instructors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_offerings',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.courses'),
        ),
    ]
