# Generated by Django 4.2.7 on 2023-12-23 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_teacher_offering_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_offering',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
