# Generated by Django 4.2.7 on 2023-12-23 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_teacher_offering_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_offering',
            name='student',
        ),
    ]
